# Generated by Django 2.0.2 on 2018-02-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=100)),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
